language: node_js
node_js:
  - "4"
script:
  - gulp build
deploy:
    provider: s3
    access_key_id: $AWS_ACCESS_KEY # declared in Travis repo settings
    secret_access_key: $AWS_SECRET_KEY
    bucket: static.cifrascatolicas.com.br
    region: sa-east-1
    skip_cleanup: true
    local-dir: build
    acl: public_read
    detect_encoding: true
notifications:
    email:
        on_failure: always
